"""Block a git commit whose message carries AI attribution.

OFF by default: this file ships, but .claude/settings.json does not call it. To switch it on,
add this next to the "PostToolUse" entry in .claude/settings.json:

    "PreToolUse": [
      {
        "matcher": "Bash|PowerShell",
        "hooks": [
          {
            "type": "command",
            "command": "H=\"${CLAUDE_PROJECT_DIR}/.claude/hooks/guard_commit.py\"; [ -f \"$H\" ] || exit 0; if [ \"$OS\" = \"Windows_NT\" ]; then P=python; else P=python3; fi; \"$P\" \"$H\""
          }
        ]
      }
    ]

Once on, it runs before every shell command. It stays silent unless the command is a git commit
AND the text contains an attribution marker. Any problem inside the hook itself exits 0, because
a broken guard must never block normal work.
"""
import json
import re
import sys

# Specific markers only. A bare "claude" would also hit paths like .claude/ in the same command.
MARKERS = [
    r"co-authored-by",
    r"generated with \[?claude",
    r"generated by claude",
    r"noreply@anthropic\.com",
    "\U0001F916",  # the robot emoji some tools append
]
COMMIT = re.compile(r"\bgit\b[^\n]*\bcommit\b")


def main():
    try:
        # Read bytes: the Windows console encoding cannot decode every UTF-8 character.
        data = json.loads(sys.stdin.buffer.read().decode("utf-8", "replace"))
        command = (data.get("tool_input") or {}).get("command") or ""
    except Exception:
        return 0
    if not COMMIT.search(command):
        return 0
    text = command.lower()
    found = [m for m in MARKERS if re.search(m, text)]
    if not found:
        return 0
    print("Blocked: this git commit carries AI attribution (matched: " + ", ".join(found) + "). "
          "This project's rule is no AI attribution in commits. Remove it and commit again.",
          file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
